## LATIHAN

Diketahui Array :[26 07 05] Tanggal Lahir

                 [86 20 06]  Digit No Hp

Lakukanlah Operasi:
                

1. Perkalian Matrix

In [2]:
# TTL   : 26 Juli 2005
# No Hp : 081378862006

import numpy as np

A = np.array([[2,6],[0,7],[0,5]])
B = np.array([[8,6],[2,0],[0,6]])

kali = A * B
print(kali)

[[16 36]
 [ 0  0]
 [ 0 30]]


2. Pengurangan Matrix

In [3]:
import numpy as np

A = np.array([[2,6],[0,7],[0,5]])
B = np.array([[8,6],[2,0],[0,6]])

kurang = A - B
print(kurang)

[[-6  0]
 [-2  7]
 [ 0 -1]]


3. Transpose Matrix

In [4]:
import numpy as np

A = np.array([[2,6],[0,7],[0,5]])
B = np.array([[8,6],[2,0],[0,6]])

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

print(transpose_A)
print(transpose_B)

[[2 0 0]
 [6 7 5]]
[[8 2 0]
 [6 0 6]]


4. Nilai Invers

In [6]:
import numpy as np

A = np.array([[2,6],[0,7]])
B = np.array([[8,6],[2,0]])


invers_A = np.linalg.inv(A)
invers_B = np.linalg.inv(B)

print("\nInvers matrix A :")
print("\nInvers matrix B :")
print(invers_A)
print(invers_B)



Invers matrix A :

Invers matrix B :
[[ 0.5        -0.42857143]
 [ 0.          0.14285714]]
[[ 0.          0.5       ]
 [ 0.16666667 -0.66666667]]


5. Nilai Determinan

In [7]:
import numpy as np

A = np.array([[2,6],[0,7]])
B = np.array([[8,6],[2,0]])

determinant_A = np.linalg.det(A)
determinant_B = np.linalg.det(B)
print("Determinan dari matrix A:", determinant_A)
print("Determinan dari matrix B:", determinant_B)

Determinan dari matrix A: 13.999999999999996
Determinan dari matrix B: -11.999999999999995
